#!/bin/sh
. ./parameter.cfg
sam build
cd .aws-sam/build
aws cloudformation package \
    --region $REGION \
    --template-file template.yaml \
    --s3-prefix $PROJECT_NAME \
    --s3-bucket $S3_BUCKET \
    --output-template-file packaged.yaml
aws cloudformation deploy \
    --stack-name $PROJECT_NAME \
    --template-file packaged.yaml \
    --region $REGION \
    --capabilities CAPABILITY_NAMED_IAM  \
    --s3-bucket $S3_BUCKET \
    --s3-prefix $PROJECT_NAME \
    --parameter-overrides \
        ProjectName=$PROJECT_NAME \
        RolePath=$ROLE_PATH \
        ZoomVerificationToken=$ZOOM_VERIFICATION_TOKEN \
        BoxClientId=$BOX_CLIENT_ID \
        BoxClientSecret=$BOX_CLIENT_SECRET \
        BoxEnterpriseId=$BOX_ENTERPRISE_ID \
        BoxJwtKeyId=$BOX_JWT_KEY_ID \
        BoxFolderId=$BOX_FOLDER_ID \
        BoxUser=$BOX_USER \
        BoxPrivateKeyId="$BOX_PRIVATE_KEY_ID"

